### ISSUE TITLE
Maak motie button is gone in motie categorie

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#101]
Motie category should have maak motie button and meest gesteund.
<img width="1225" alt="screen shot 2016-11-05 at 08 11 55" src="https://cloud.githubusercontent.com/assets/11832800/20028356/9b5f3ad8-a32f-11e6-9c6d-275e09bb82a9.png">

**Comment by kgish** [comment]
Bummer, I'll look into it right away.
