### ISSUE TITLE
Implement bootbox

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#111]
Replace use of ugly alert boxes with the nicer and more elegant [Bootbox.js](http://bootboxjs.com/).

I will do this free of charge.

**Comment by Socioneers** [comment]
Great, thanks.

Is er also a possibility to see the total amount of likes in the green box instead of the ones of the latest annotation?


PS PvdA admin prefers not to have any changes on production, because he is affright people will get confused.

**Comment by kgish** [comment]
Hi Raoul,

Currently that's what it already does, all likes from everyone for that 
given annotation. Not sure what you mean, total amount of which likes?

No worries, I've created a separate development branch so none of my 
fixes will get propagated to production unless I manually merge them 
into the master branch and tag it there.

Each new issue and/or task will get its own feature branch and when 
verified is merged back to development.

The test server will now only get the latest development when rebuilt.

Only when we are satisfied that test is fine will be deploy to 
production (ideally first to staging, whenever you want this).

Regards,

Kiffin

-- 
Kiffin Gish

Advanced Software Development for the Web
http://gishtech.com

**Comment by Socioneers** [comment]
I will call you.
