### ISSUE TITLE
Recover disappearing annotations

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#114]
If a topic contents is modified, the annotations that were created before the change date will no longer be visible and/or not correlate with available text.

Right now if a given annotation highlight cannot be found
```
<span class='annotator-hl" data-annotator-id="234">...</span>
```
I just skip the annotation and generate an error message to the console.

**Comment by Socioneers** [comment]
Original document tekst seem to have been changed by one of us admins > see the toevoeging that is actually part of the amendment

Changed tekst now on platform.
• Toevoeging: er moet meer energie gestoken worden in de preventie. Voorkomen moet worden dat kwetsbare mensen verwarde mensen worden.

Wij willen gemeenten meer geld geven voor de opvang van verwarde mensen. Mensen met een ggz-indicatie worden zoveel mogelijk thuis opgevangen en behandeld. De omgeving en familie worden hierbij betrokken.

•	In elke wijk moet er ambulante ggz-zorg beschikbaar zijn voor die situaties dat thuis wonen even geen optie is voor de patiënt.

•	We zien de noodzaak voor meer samenwerking tussen sociale wijkteams, ambulante zorgverleners en specialisten en stimuleren deze samenwerking.

•	Wij willen politie en hulpdiensten beter trainen in het herkennen en omgaan van mensen die verward zijn. We breiden het aantal plekken voor crisisopvang uit, zodat verwarde mensen niet onnodig in de cel belanden of op straat blijven met alle gevaar van dien.


Original tekst.
GGZ
Wij willen gemeenten meer geld geven voor de opvang van verwarde mensen. Mensen met een ggz-indicatie worden zoveel mogelijk thuis opgevangen en behandeld. De omgeving en familie worden hierbij betrokken. 
In elke wijk moet er ambulante ggz-zorg beschikbaar zijn voor die situaties dat thuis wonen even geen optie is voor de patiënt. 
We zien de noodzaak voor meer samenwerking tussen sociale wijkteams, ambulante zorgverleners en specialisten en stimuleren deze samenwerking. 
Wij willen politie en hulpdiensten beter trainen in het herkennen en omgaan van mensen die verward zijn. We breiden het aantal plekken voor crisisopvang uit, zodat verwarde mensen niet onnodig in de cel belanden of op straat blijven met alle gevaar van dien.

**Comment by Socioneers** [comment]
https://ledenkamer.pvda.nl/t/8-5-ggz-amendeerbaar/388# <https://ledenkamer.pvda.nl/t/8-5-ggz-amendeerbaar/388#>
