### ISSUE TITLE
Highlight plugin if referred to in url

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#117]
If someone is using an annotation link and the anchor `#annotator_123` is present in the url, then highlight the annotation using the site settings.

**Comment by kgish** [comment]
![screenshot from 2016-11-23 13-32-08](https://cloud.githubusercontent.com/assets/79195/20561920/465743ea-b181-11e6-8480-1a8426ac26ae.png)

![screenshot from 2016-11-23 13-31-41](https://cloud.githubusercontent.com/assets/79195/20561927/4d4dfac2-b181-11e6-9557-dde30757c2e7.png)

**Comment by Socioneers** [comment]
Is it also possible to highlight the right-side indicator?

**Comment by kgish** [comment]
Sure it's possible, but why? Seems that the highlighted text should be enough. Or do you want the user to have an easy why to click open the thread related to that annotation?

**Comment by Socioneers** [comment]
Or that the sidebar opens automatically.

Thinking about budget lets park this.

**Comment by kgish** [comment]
This isn't too difficult, I'd still like to give it a try.

**Comment by kgish** [comment]
![screenshot from 2016-12-13 18-17-25](https://cloud.githubusercontent.com/assets/79195/21151242/0d135ee8-c162-11e6-8dc6-d0d798ec919a.png)

**Comment by kgish** [comment]
In action:

**Comment by kgish** [comment]
Completed, here's the scenario:

1. The user uses the shared link and arrives at the topic.
2. The application detects the query string in the url and uses that to match the location of the shared annotation.
3. The text is selected, colorized according to the site setting `annotator highlight anchor`.
4. The row on which it is located is determined in order to open up the sliding panel with the correct listing of all annotation starting on the same line.
5. Finally, if the relevant annotation is not the topmost entry, the sliding panel is scrolled upwards so that the correct entry is positioned at the top.
