### ISSUE TITLE
Add up vote nr at right side indicator

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#120]
Now you see only the amount of votes and comments on the last amendment. Would be an improvement if you could see the total of comments and votes per rule.

**Comment by Socioneers** [comment]
<img width="188" alt="screen shot 2016-12-07 at 15 11 47" src="https://cloud.githubusercontent.com/assets/11832800/20971066/6981ed06-bc90-11e6-9007-194ad14126af.png">

**Comment by Socioneers** [comment]
Maybe make the color of the amendment block red and swop it with the vote block.

**Comment by kgish** [comment]
Yes I can do this. I will start with values for all of the amendments on that line.

Change:
```
[#annotations][#comments][#likes] Amendmentent(en)
```
to
```
[#likes][#comments][#annotations] Amendmentent(en)
```

**Comment by Socioneers** [comment]
<img width="179" alt="screen shot 2016-12-07 at 15 11 47" src="https://cloud.githubusercontent.com/assets/11832800/21007169/10c1c252-bd3c-11e6-8375-37e77297b465.png">

And than swop [#likes] Steun [#annotations] Amendmentent(en)

And swop the grey colour

**Comment by Socioneers** [comment]
#0e76bd instead of grey

**Comment by kgish** [comment]
Site settings will now allow the order as well as the text.

![screenshot from 2016-12-13 12-30-51](https://cloud.githubusercontent.com/assets/79195/21138809/16d0dc6c-c130-11e6-9286-325b71a29b0d.png)

**Comment by kgish** [comment]
![screenshot from 2016-12-13 14-41-35](https://cloud.githubusercontent.com/assets/79195/21142418/44d9475e-c142-11e6-91bf-fbb9cf438010.png)
