### ISSUE TITLE
Sidebar adjustments clipboard 

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#121]
Replace tekst: Kopieer naar clipboard > Kopieer naar klembord

<img width="498" alt="screen shot 2016-12-14 at 13 13 17" src="https://cloud.githubusercontent.com/assets/11832800/21181936/a0d88376-c200-11e6-9fad-9661bccd3858.png">

**Comment by kgish** [comment]
Okay, this is an easy one.

**Comment by Socioneers** [comment]
Klemboard > Klembord

**Comment by Socioneers** [comment]
Kopieer button does not properly select url 
Now I copy past it by hand

**Comment by kgish** [comment]
Yes I noticed that.

**Comment by kgish** [comment]
Seems to be working now, please double check.
