### ISSUE TITLE
Steun/ gesteund button sidebar

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#122]
Steun + bigger plus + steun/ gesteund button

<img width="236" alt="screen shot 2016-12-14 at 13 25 05" src="https://cloud.githubusercontent.com/assets/11832800/21181961/cadd84b4-c200-11e6-9fd4-f112f5bd358a.png">

or
<img width="498" alt="screen shot 2016-12-14 at 13 13 17" src="https://cloud.githubusercontent.com/assets/11832800/21182011/21a70cde-c201-11e6-9789-d118e46341e9.png">
<img width="498" alt="screen shot 2016-12-14 at 13 13 17" src="https://cloud.githubusercontent.com/assets/11832800/21182044/45bbbad4-c201-11e6-9718-4151bd0afc30.png">

**Comment by kgish** [comment]
Does this mean that you `unvoting` is no longer allowed?

**Comment by Socioneers** [comment]
No unvoting is still allowed, looking to make the voting possibility look more clear. Trying to find a way to have a clearer button with text > steun > gesteund

**Comment by kgish** [comment]
Let's keep the interface as simple as possible.

To avoid cluttering things up, I could just ask the user if he wants to downvote if he clicks again on the [Gesteund]-button.

What should be the Dutch text?

**Comment by Socioneers** [comment]
Yes I think we understand each other.

Steun and Gesteund

Click gesteund to unvote.

**Comment by kgish** [comment]
Agreed. Assuming no need to ask user if he's sure, just toggle clicks as is. Will replace the icons with a button.

**Comment by kgish** [comment]
Did you also want the `Deel` link to be shifted to the left as shown in the screenshot?

**Comment by Socioneers** [comment]
No don’t think so.

Thanks

**Comment by kgish** [comment]
![screenshot from 2016-12-14 21-32-23](https://cloud.githubusercontent.com/assets/79195/21199779/36fb045c-c245-11e6-806f-4fb76371859b.png)
![screenshot from 2016-12-14 21-32-36](https://cloud.githubusercontent.com/assets/79195/21199780/370e4b98-c245-11e6-8224-75eed8c31074.png)

**Comment by Socioneers** [comment]
Very clear like this!

**Comment by Socioneers** [comment]
Not visible, in this update.

**Comment by kgish** [comment]
Need to update the site settings:

![screenshot from 2016-12-15 11-49-46](https://cloud.githubusercontent.com/assets/79195/21221331/3f0c7f68-c2bd-11e6-987f-502fb804ade6.png)

and:

![screenshot from 2016-12-15 11-55-19](https://cloud.githubusercontent.com/assets/79195/21221364/5f4dc8a4-c2bd-11e6-874e-b62976911cbd.png)

Please try again.
