### ISSUE TITLE
Mail button in header

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#125]
If possible the internal mail button in header.

**Comment by Socioneers** [comment]
<img width="282" alt="screen shot 2016-12-14 at 14 07 07" src="https://cloud.githubusercontent.com/assets/11832800/21183194/0c0ff830-c207-11e6-8e85-52cd55c98f3b.png">

**Comment by kgish** [comment]
Do not understand, where is this and what does this button supposed to do? Please explain.

**Comment by Socioneers** [comment]
We want to promote user to use the internal mailing system more.

<img width="425" alt="screen shot 2016-12-14 at 14 55 41" src="https://cloud.githubusercontent.com/assets/11832800/21184594/6bd685c6-c20d-11e6-94a1-ad91d71b9260.png">

**Comment by kgish** [comment]
Okay, good idea!

**Comment by kgish** [comment]
Site setting.
![screenshot from 2016-12-15 21-32-23](https://cloud.githubusercontent.com/assets/79195/21240976/fd89c3c4-c30d-11e6-8eb4-5fd7b42bbb54.png)

Email icon.

![screenshot from 2016-12-15 21-33-28](https://cloud.githubusercontent.com/assets/79195/21241026/24bc5b5a-c30e-11e6-81d4-e3c6b8506045.png)
