### ISSUE TITLE
In test enviroment nieuwe motie button

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#126]
@ test server nieuwe motie button is nieuw onderwerp button.

I will compare settings first.

**Comment by kgish** [comment]
Yes, there was recently a big update of the language files and I did my best to merge our updates. Might have missed something, requested a review earlier.

**Comment by kgish** [comment]
Will look at it now.

**Comment by kgish** [comment]
Fixed, please verify.

**Comment by Socioneers** [comment]
Now the nieuwe motie button is in every category. Should be only in motie category.
<img width="1200" alt="screen shot 2016-12-20 at 14 37 29" src="https://cloud.githubusercontent.com/assets/11832800/21352496/01557ebe-c6c2-11e6-81e6-433b2d96639c.png">

**Comment by kgish** [comment]
Not good, will fix.

**Comment by kgish** [comment]
Something else is doing this, not my code. Perhaps configuration?

**Comment by kgish** [comment]
Even when I disable the pvda and annotator plugins, the text "Nieuwe Motie" still appears, weird ...

**Comment by Socioneers** [comment]
I found the problem. With the new translation file “Nieuwe Onderwerp” slipped in which should be "Nieuw Onderwerp”.
When I change it correctly in beheer it works how it should be working.

**Comment by Socioneers** [comment]
What was the link to the translation file again?

**Comment by kgish** [comment]
Good job. You need to update [client.nl.yml](https://github.com/kgish/discourse-pvda-plugin/blob/master/discourse-socioneers/config/locales/client.nl.yml).

**Comment by Socioneers** [comment]
Done

**Comment by kgish** [comment]
This has been fixed, right?

**Comment by Socioneers** [comment]
Yes fixed.
