### ISSUE TITLE
Remove possibility to comment

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#16]
In the popup view box the user should not be able to add comments, so remove.

**Comment by kgish** [comment]
![annotator-new-and-improved](https://cloud.githubusercontent.com/assets/79195/18482964/87b850e4-79e2-11e6-9ed6-9c4677fab556.png)

**Comment by Socioneers** [comment]
In this way it is better yes. But now in test I see the hover over > I assumed you turned it on again to vote?

**Comment by Socioneers** [comment]
fixed
