### ISSUE TITLE
Annotate functions only @ amendment catagory

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#21]

**Comment by kgish** [comment]
I believe that this is already the case: annotation is only enabled on the pages with category as defined in the site settings, by default it is now set to 'motie'.

Is this correct or do you mean something else?

**Comment by Socioneers** [comment]
Yes so function should only be enabled on amendeer category level (see example how its done with voting) but could also be configured at plugin admin level in the future
 
<img width="674" alt="screen shot 2016-09-21 at 12 40 20" src="https://cloud.githubusercontent.com/assets/11832800/18707973/c5138fbe-7ff8-11e6-8146-aee91232b9d7.png">

**Comment by Socioneers** [comment]
Some pieces of text should not be abled to annotate. We would like or put them in a different category or close the topic.

**Comment by Socioneers** [comment]
Kiffin, could you have a look at this issue (or a css fix) is important for tuesday?

**Comment by Socioneers** [comment]
Kiffin, could you have a look at this issue is important for tuesday?

**Comment by kgish** [comment]
I will have a look at it this today.

**Comment by kgish** [comment]
![screenshot from 2016-10-14 19-59-44](https://cloud.githubusercontent.com/assets/79195/19397614/cace40ae-9248-11e6-96f9-335f47d89926.png)

**Comment by kgish** [comment]
Please verify.
