### ISSUE TITLE
Make it possible to vote and remove vote in sidebar

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#23]

**Comment by kgish** [comment]
@Socioneers : Can you please explain what this means?

**Comment by Socioneers** [comment]
so that you can vote as a user on the amendmend

**Comment by kgish** [comment]
Please note that in the current setup it is not possible to cancel a vote when only the likes (green) is present.

Therefore, in order to make this possible, I've included the flags (red).

In order to avoid confusion (I hope), I've renamed these two buttons:
```
like(s) => upvote(s)
flag(s) => downvot(e)
```

While I was at it, I also translated all of the English words into Dutch, so please check that my translations are also correct.

**Comment by kgish** [comment]
Rebuilt the test server.

**Comment by kgish** [comment]
Come to think of it, I could design the like (upvote) so that the first time it is clicked the vote is incremented by one and the second it is clicked by the same person it is decremented by one (cancelled).

However, this would mean changing the server into something that is different from the annotatorjs (madison) specifications.

**Comment by Socioneers** [comment]
issue merge with: #42
