### ISSUE TITLE
Remove “Nieuw onderwerp” button @ amendeer catogorie

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#32]

**Comment by kgish** [comment]
Please explain what this means.

**Comment by Socioneers** [comment]
In the "amendeer category" only admins should be able to make new topics/onderwerpen

**Comment by kgish** [comment]
Isn't this something that can be done via the admin dashboard?

Or do you want me to disable/hide the new-button if `user.admin == false`

**Comment by Socioneers** [comment]
fixed

**Comment by Socioneers** [comment]
in subcategory the “New topic/ nieuw onderwerp” button reappears.
<img width="1168" alt="screen shot 2016-10-23 at 09 15 56" src="https://cloud.githubusercontent.com/assets/11832800/19624674/42ea2214-9902-11e6-8d7e-9cfe84a8a9b8.png">

**Comment by Socioneers** [comment]
On test I see that it works with the newer category, the older categories have still the nieuw onderwerp button.

**Comment by kgish** [comment]
You will need to update the annotator- and/or pvda- categories list in the admin dashboard

This is related to [comments issue #58](https://github.com/kgish/discourse-annotator-plugin/issues/58#issuecomment-255602880).
