### ISSUE TITLE
Hide Quote function @ amendeer catogorie

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#33]
Discourse quote toolbar pops up `quote reply` when selecting text which interferes with the normal operation of the annotation plugin, also own toolbar popup.

**Comment by kgish** [comment]
https://meta.discourse.org/t/disable-the-quote-reply-popup/50161

**Comment by kgish** [comment]
```
.quote-button { display: none !important; }
```

**Comment by Socioneers** [comment]
Seems to be disabled in all categories.

**Comment by kgish** [comment]
Not good, will check.
