### ISSUE TITLE
Remove flaggen

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#36]

**Comment by kgish** [comment]
Fixed. This can now be disabled by removing `flags` from the site settings `sidebar_format` which looks like this:
```
annotations,comments,likes,flags,author,quote,created
```
By default the `flags` is not present and therefore disabled.

**Comment by Socioneers** [comment]
Fixed, but we would like only voting option

**Comment by kgish** [comment]
See above. Have you tried including the `likes` in the `sidebar_format` option in the admin dashboard plugins?

**Comment by kgish** [comment]
What was the status on this one?

**Comment by Socioneers** [comment]
need to try cant get on the test version

**Comment by Socioneers** [comment]
Ok seems to work, though I down voting will not go well with the client. Maby you can remove the number in the red box or make the number red so you wont see it + change the down vote in remove vote.

**Comment by kgish** [comment]
Makes sense what you are saying. Don't want to disappoint the customer.

I can come up with another solution without having to use the red flag.

For example, if someone has already voted then an extra link or button appears next to the vote button to cancel vote, like a cross.

Clicking the cross will cancel vote, enable vote button and cross will disappear.

How does that sound?

**Comment by Socioneers** [comment]
Sounds good, I would go for what is easiest to do.

**Comment by Socioneers** [comment]
related to #42
