### ISSUE TITLE
Remove flag function and move vote function to sidebar

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#42]

**Comment by Socioneers** [comment]
Should be possible to "remove" your vote

**Comment by kgish** [comment]
Same with the flag?

**Comment by Socioneers** [comment]
why is it closed?

**Comment by kgish** [comment]
Oops, my mistake.

**Comment by kgish** [comment]
![untitled](https://cloud.githubusercontent.com/assets/79195/19038950/3281269a-897e-11e6-8e68-05072032fe59.png)


![screenshot from 2016-10-03 15 23 44](https://cloud.githubusercontent.com/assets/79195/19038900/f6c26ad8-897d-11e6-81ec-8b229f961188.png)

**Comment by Socioneers** [comment]
Looks good!

**Comment by Socioneers** [comment]
Looks good!

**Comment by kgish** [comment]
Were you also able to test it for multiple annotations per topic or per line?

How about actual data with many users?

**Comment by Socioneers** [comment]
good idea to test it with more annotation
