### ISSUE TITLE
Annotate function off when topic closed

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#49]
When a topic is closed then it should not be possible anymore for the user to create more annotations.

**Comment by Socioneers** [comment]
When topic is open you still can annotate

**Comment by Socioneers** [comment]
Not fixed, I can annotate all topics

**Comment by kgish** [comment]
Not good, something went wrong with the upgrade. I will have a look.

I can see that the pages are marked as closed topics, so there must be something else going wrong.

**Comment by Socioneers** [comment]
Now it kind of works, strange, shows now only popup

**Comment by kgish** [comment]
What do you mean it "kind of works" ? In what situation does it not work? Can you define a reproducible set of steps?

**Comment by kgish** [comment]
Assuming fixed, close.
