### ISSUE TITLE
Put extra button in annotate dialog box > edit > schrappen (remove text)

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#50]

**Comment by Socioneers** [comment]
Need to bring back the to options within the annotator popup where you can chose to annotate or edit. These functions need to be translated in annotate > toevoegen / veranderen (add/ change) and edit > schrappen (remove text)

**Comment by kgish** [comment]
I believe that you are referring to permissions option located in the admin dashboard plugin settings. Does checking the following checkbox do the trick?

![annotator-widget-edit-permissions](https://cloud.githubusercontent.com/assets/79195/18709584/289e62fe-8001-11e6-81ba-4273038b9eb8.png)

**Comment by Socioneers** [comment]
Do you need feedback from me?

**Comment by kgish** [comment]
Yes, see question above with screenshot annotator widget edit.

**Comment by Socioneers** [comment]
Yes does the trick, but still not sure how the functions are different. And are able to do what client wants

**Comment by kgish** [comment]
Still need to translate to Dutch.

**Comment by kgish** [comment]
What do you mean by `edit > schrappen (remove text)` ?

The edit-button can be selected for proposing changes to the text, whereas the annotate-button (toevoegen) is used for linking annotations to the selected text.

**Comment by kgish** [comment]
Please respond.

**Comment by Socioneers** [comment]
It is fixed but edit still bit buggy

**Comment by Socioneers** [comment]
put extra butten in annotate dialog box >  edit > schrappen (remove text)

**Comment by kgish** [comment]
Don't understand. Right now there are two possibilities: Bewerken (edit) and Toevoegen (create).

Do you want me to place a 3rd button there called 'Schrappen' ? 

What is the purpose of this button?

**Comment by Socioneers** [comment]
Do you want me to place a 3rd button there called 'Schrappen' ? > Yes with the same function as bewerken.

What is the purpose of this button? > because they are used to having three ways to make an amendment and is easier to copy and place the button than trying to discuss using 2 buttons...

**Comment by kgish** [comment]
I (finally) understand, will get on with it and hopefully have ready before tomorrow noon.

**Comment by kgish** [comment]
Whew, just in time for the demo this afternoon. Hope they like it ...

**Comment by Socioneers** [comment]
Great is it possible to have a line through the deleted text?
<img width="328" alt="screen shot 2016-10-10 at 11 56 16" src="https://cloud.githubusercontent.com/assets/11832800/19232552/b5edb180-8ee0-11e6-9b04-01c0ae2dce50.png">
<img width="328" alt="screen shot 2016-10-10 at 11 56 16" src="https://cloud.githubusercontent.com/assets/11832800/19232583/d1541928-8ee0-11e6-8cb0-0199c1f20885.png">

**Comment by kgish** [comment]
Yes of course, no problem.
