### ISSUE TITLE
Created annotations should be public by default

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#51]
Currently (since the widget edit popup changed to hide this), it is no longer possible to make your annotation public, e.g. only the author can see it.

Add `create-public` site setting which when enabled (checked) will allow anyone to view it.

**Comment by Socioneers** [comment]
By people in the pvda "group"

**Comment by kgish** [comment]
Is this the same as #50?

**Comment by Socioneers** [comment]
#51 is about view privilege and not related to #50 that is about edit functionality when you make your annotation.

**Comment by Socioneers** [comment]
Verified
