### ISSUE TITLE
Sidebar scroll area below bottom of the screen

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#53]
The annotations sidebar gets extended too far in the y-direction (autoscroll) and needs to be re-adjusted so that the annotations list area remains completely visible in the available area.

Just keep submitting new comments until the final input field and submit button get pushed below the bottom of the screen.

**Comment by kgish** [comment]
Fixed with #44.

**Comment by kgish** [comment]
Please verify.

**Comment by Socioneers** [comment]
Don't see the problem> could you explain more.

**Comment by kgish** [comment]
The problem is now fixed, so you won't see it anymore ;)

Before the fix, the scrolling area went down below the bottom of the page and you weren't able to see the last stuff.
