### ISSUE TITLE
Timeline stacking order obscures widget

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#54]
<img width="864" alt="screen shot 2016-09-28 at 13 35 40" src="https://cloud.githubusercontent.com/assets/79195/18914953/7867acee-858f-11e6-8d68-c4d095829702.png">

**Comment by kgish** [comment]
This is a tricky one. After a couple hours pounding my head against the wall, I decided to ask for help from the experts via the Discourse forum.

https://meta.discourse.org/t/timeline-z-index/50797/1

**Comment by kgish** [comment]
https://philipwalton.com/articles/what-no-one-told-you-about-z-index/

**Comment by Socioneers** [comment]
As long users don't use the reply button, timeline will not be created. When topic is used voor amendement reply button should not be used. So problem is solved.
