### ISSUE TITLE
remove "nieuw onderwerp" in share popup

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#57]
see picture and red circle
![screen shot 2016-09-30 at 11 36 33 2](https://cloud.githubusercontent.com/assets/11832800/19006101/3cdc7846-875e-11e6-90ad-ed138652a46b.png)

**Comment by kgish** [comment]
This has nothing to do with the annotator and needs to be fixed in the pvda-plugin. Close this issue and move it to https://github.com/kgish/discourse-pvda-plugin/issues/33.
