### ISSUE TITLE
Check if settings don't conflict when amendments and motions happen in same period

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#59]
Users will be able to file motions in the same period as amendments happen 15 okt- 15 nov 2016

**Comment by kgish** [comment]
I do not understand, please explain better.

**Comment by Socioneers** [comment]
As example we need to have the blue background on at the motion category and turned of at the amendeer category

**Comment by Socioneers** [comment]
Yes it conflicts, see issue #21

**Comment by kgish** [comment]
I believe that this has been fixed and/or has become a non-issue, close?
