### ISSUE TITLE
Switch motie blue background off

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#61]
maybe split pvda plugin in motie plugin and annotate or pvda style plugin

**Comment by kgish** [comment]
This can be done ind the plugin settings.

Don't understand the part about splitting things up, please explain.

**Comment by kgish** [comment]
Motie background color is done by the pvda-annotator, see: https://github.com/kgish/discourse-pvda-plugin/issues/34.

**Comment by kgish** [comment]
Moved to https://github.com/kgish/discourse-pvda-plugin/issues/35.
