### ISSUE TITLE
Reason bewerken is not visable in foldout

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#62]
I think previously I asked to code it away but we seem to need it again.
<img width="428" alt="screen shot 2016-09-30 at 23 07 22" src="https://cloud.githubusercontent.com/assets/11832800/19007012/dfd579ea-8762-11e6-9553-83db18f8240b.png">
<img width="547" alt="screen shot 2016-09-30 at 23 07 36" src="https://cloud.githubusercontent.com/assets/11832800/19007011/dfd51bc6-8762-11e6-9dc4-115463463eb9.png">

**Comment by kgish** [comment]
Not sure if this possible, but I will have a look.

**Comment by kgish** [comment]
Nothings impossible for the Mighty Gish.

**Comment by Socioneers** [comment]
ᕙ(⇀‸↼‶)ᕗ

**Comment by kgish** [comment]
Verified?

**Comment by Socioneers** [comment]
still the same fault message

**Comment by kgish** [comment]
Try one more time please (fingers-crossed).
