### ISSUE TITLE
Deel link naar dit bericht

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#63]
The current deel link in the sidebar is ugly, make it look more discourse-like:

Deel link naar dit bericht:
![deel-een-link-naar-dit-bericht](https://cloud.githubusercontent.com/assets/79195/19016667/a676004c-8821-11e6-8ba2-42e939d1f408.png)

**Comment by Socioneers** [comment]
I think this should be parked for now.

**Comment by kgish** [comment]
#share-link

<div id="share-link" class="ember-view visible" style="top: 430px; left: 904.641px;"><h3>Caption</h3>
    <div>
      <input type="text">
    </div>    
    <div class="link">
      <a href="" data-ember-action="2031" aria-label="sluit" title="sluit"><i class="fa fa-close"></i></a>
    </div>
</div>
