### ISSUE TITLE
Instead of user name "amendementen" after right-side indicators

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#70]
I think the compiling of amendementen is a good idea and user friendly, could you remove the username at right indicator and replace it with amendementen.

<img width="485" alt="screen shot 2016-10-10 at 11 25 31" src="https://cloud.githubusercontent.com/assets/11832800/19231817/79e5ecba-8edc-11e6-9c2c-29f7a2967d61.png">

**Comment by kgish** [comment]
Boring, so want the same word to be repeated all over the place? Alright, will do.
