### ISSUE TITLE
Change text sidebar: Aantekeningen

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#73]
Aantekeningen > Amendementen
<img width="553" alt="screen shot 2016-10-11 at 15 19 51" src="https://cloud.githubusercontent.com/assets/11832800/19272151/badec462-8fc7-11e6-9b43-d9d827663b81.png">

**Comment by Socioneers** [comment]
Is still Aantekeningen > should be Amendementen

**Comment by kgish** [comment]
Weird, something must have gone wrong with the deploy. Will try again.

**Comment by kgish** [comment]
Please wait until tomorrow after I've updated the test server before verifying.
