### ISSUE TITLE
What to do with annotator-server

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#78]
Currently we are still using https://powerful-lowlands-24881.herokuapp.com which is my private Heroku account.

In the long term having an external datastore is probably not what pvda wants.

Need to decide what to do, e.g. internal server setup within the pvda infrastructure.

**Comment by kgish** [comment]
Bumped heroku server up to standard high performance so we can park this one for the time being.

**Comment by Socioneers** [comment]
I prefer to have the annotation data stored in the discourse database https://meta.discourse.org/t/create-custom-db-table-and-fields-from-plugin/36164/4

I also had a link referring to an article about storing annotatorjs output on same database en server as the mother platform. I will try to find it back.

**Comment by kgish** [comment]
Yes I already know the basics on how to do this. However, it'll be a significant amount of work. Another disadvantage will be that your annotator product will no longer be an independent service and instead will become tied irreversibly into discourse (thinking about the future and other customers that might want to use it but use a different platform/cms than discourse.

**Comment by kgish** [comment]
Shall I come up with a planning estimate?

**Comment by Socioneers** [comment]
Reading your feedback it looks it is better/ cheaper todo it in the way we have already planned > on the same pvda vps, I think you and michael need to figure out a few things. Can you pick that up with Michael?

(I had this storage idea because it could help with notification within the discourse system.. But I think it will not fit in the budget for now and the improved annotation share link improves notification possibilities.)

**Comment by kgish** [comment]
Will do.

**Comment by kgish** [comment]
Finally fixed with a slight hack, meaning that I had to change one of the low-level annotator library souce files.

In order to get the store plugin to work properly with the annotator store server, it was necessary for me to make the following changes in the `store.coffee` file:

Original:

```
 _onLoadAnnotationsFromSearch: (data={}) =>
    this._onLoadAnnotations(data.rows || [])
```
Changed:

```
 _onLoadAnnotationsFromSearch: (data={}) =>
    this._onLoadAnnotations(data.rows || data || [])
```

This covers the case where the response doesn't use the `rows` as root:
```
{ rows: [{...},{...}], ... }
```

but simply returns the an array of annotations directly:
```
[{...},{...}]
```

While remaining backwards compatable with the original default case.

**Comment by kgish** [comment]
In the site settings, need to revert the value of `annotator_store_url` to: https://server5.socioneers.com:3030

**Comment by Socioneers** [comment]
Yeah!
