### ISSUE TITLE
After refresh annotation disappears!

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#80]
system does not seem to save them

Is this related?>
Er is al een tijdje niet op updates gecontroleerd. Zorg dat sidekiq loopt." <<

**Comment by kgish** [comment]
Can you please point me to the exact page where this is happening so that I can investigate.

**Comment by Socioneers** [comment]
Has to do with michael’s server settings. Sorry

so can be closed

**Comment by kgish** [comment]
Great, relieved that you were able to fix the problem. Thanks.

**Comment by Socioneers** [comment]
I had him on the phone and didn't realise the annotator plugin was still set on his server settings.

**Comment by kgish** [comment]
Well, we're all working pretty hard and it's not always possible to keep everything under raps.
