### ISSUE TITLE
' Bewerken'  in de amendeerknop moet worden: ' Wijzigen' 

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#81]

**Comment by Socioneers** [comment]
Not changed yet, maby rebuild?
<img width="465" alt="screen shot 2016-10-20 at 08 16 28" src="https://cloud.githubusercontent.com/assets/11832800/19548279/dedd6e68-969d-11e6-863a-4f913012d1e1.png">

**Comment by kgish** [comment]
Sorry, still haven't upgraded the test server. Will notify you when I do that.

Question: did Michael revert the version to the head or is it still rebased to an earlier version he installed for the dinsdag sessie? Don't want to mess things up.

Ideally we will need to re-align the version with the latest.

**Comment by Socioneers** [comment]
Could you email michael directly, think he is not directly reading git notifications.

**Comment by kgish** [comment]
Emailed Michael and waiting for response.

**Comment by kgish** [comment]
Said it was alright to upgrade, so will do that.

**Comment by Socioneers** [comment]
Sure. That's no problem. I'm working on a SSO server, but that's not running within docker
