### ISSUE TITLE
Active button widget edit

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#82]
Als de muis over de knoppen Toevoegen, Wijzigen, Schrappen hovert worden

    alle knoppen aangezet (grijsgemaakt). Keus moet worden aangeklikt ipv hover over.

**Comment by kgish** [comment]
Indeed, this is incorrect behavior. I will fix this next.

**Comment by kgish** [comment]
![screenshot from 2016-10-22 11-56-46](https://cloud.githubusercontent.com/assets/79195/19621787/aae9c130-984e-11e6-9e2c-765f88305be2.png)

**Comment by Socioneers** [comment]
Looks great!
