### ISSUE TITLE
Edit widget buttons appear at the top of the dialog box 

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#84]
Sometimes, when opening up the annotation edit widget near the top of the page, the save/cancel buttons get shifted to the top of the popup:

![screenshot from 2016-10-22 11-50-57](https://cloud.githubusercontent.com/assets/79195/19621766/e0357538-984d-11e6-90d8-2a8cdb7874d9.png)

**Comment by Socioneers** [comment]
seems to work now

**Comment by kgish** [comment]
Hurrah! That was a tough one ...
