### ISSUE TITLE
remove "Nieuw onderwerp" button @ homepage for users

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#87]
<img width="1114" alt="screen shot 2016-10-23 at 10 00 09" src="https://cloud.githubusercontent.com/assets/11832800/19624824/9d602784-9907-11e6-9340-36caf915de78.png">

**Comment by kgish** [comment]
Added a new configuration parameter `pvda_topic_create_hide` which can be modified in the admin dashboard plugin area.

![topic-create-hide](https://cloud.githubusercontent.com/assets/79195/19628745/78cc53ea-9919-11e6-8646-7b8b7f38831f.png)
