### ISSUE TITLE
Annotator server returns 404 if user not in database

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#89]
Should return 200 with likes and flags set to 0.

Instead:

```
jquery:9173 GET http://localhost:3001/users/21267/likes?topic_id=93 404 (Not Found)
```

which is not correct.

**Comment by Socioneers** [comment]
Is this fixable?
Are annotations recorded?

**Comment by Socioneers** [comment]
‘mozHidden’ en ‘mozVisibilityState’ worden niet meer ondersteund. Gebruik in plaats daarvan ‘hidden’ en ‘visibilityState’.
 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type

> i.getLastTextNodeUpTo()
> application-fe7e5b51c5632cef81e17ac48af641117f7ac581b1108fad3c85d17dded76a61.js:64
> n.BrowserRange</e.prototype.normalize()
> application-fe7e5b51c5632cef81e17ac48af641117f7ac581b1108fad3c85d17dded76a61.js:65
> t</r.prototype.getSelectedRanges/s<()
> application-fe7e5b51c5632cef81e17ac48af641117f7ac581b1108fad3c85d17dded76a61.js:65
> t</r.prototype.getSelectedRanges()
> application-fe7e5b51c5632cef81e17ac48af641117f7ac581b1108fad3c85d17dded76a61.js:65
> t</r.prototype.checkForEndSelection()
> application-fe7e5b51c5632cef81e17ac48af641117f7ac581b1108fad3c85d17dded76a61.js:65
> L/<()
> application-fe7e5b51c5632cef81e17ac48af641117f7ac581b1108fad3c85d17dded76a61.js:64
> oe.event.dispatch()
> ember_jquery-5bc98ec46a799a78ead48d23df534d67c737906cdc100d826b0a001a8a1c1b8b.js:2
> oe.event.add/v.handle()

 
![image004](https://cloud.githubusercontent.com/assets/11832800/19857914/c3057786-9f7f-11e6-8ec1-474fcf3b7d4a.png)
![image003](https://cloud.githubusercontent.com/assets/11832800/19857915/c309999c-9f7f-11e6-946a-c963b3e0ab3a.png)
![image002](https://cloud.githubusercontent.com/assets/11832800/19857916/c30c22b6-9f7f-11e6-8b54-525a706c5c49.png)
![image001](https://cloud.githubusercontent.com/assets/11832800/19857917/c30f3ffa-9f7f-11e6-9a65-c32e4fb4c645.png)

**Comment by kgish** [comment]
Already fixed at 45,000 ft (cruising altitude), still need to test.

**Comment by kgish** [comment]
All the other stuff you added has nothing to do with the original issue. Will move them to a separate ticket and delete the comments in this issue?

**Comment by kgish** [comment]
Fixed.
