### ISSUE TITLE
Only admins are recorded on time-stamp

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#90]
**As ordinary user making an annotation**
<img width="570" alt="screen shot 2016-10-31 at 10 09 41" src="https://cloud.githubusercontent.com/assets/11832800/19857788/496978d2-9f7f-11e6-9d77-8331aecb8b73.png">
**As admin user making an annotation**
<img width="570" alt="screen shot 2016-10-31 at 10 14 10" src="https://cloud.githubusercontent.com/assets/11832800/19857789/4969f406-9f7f-11e6-9bad-228e95a25a98.png">

**Comment by kgish** [comment]
This might be related to #89, let me check.

**Comment by kgish** [comment]
Turns out that this is a restriction of discourse and therefore not a trivial fix.

I left the following request on the support forum:

https://meta.discourse.org/t/change-topic-timestamp-results-in-403-forbidden/52312

**Comment by kgish** [comment]
Also related to #74.

**Comment by kgish** [comment]
See [this suggestion](https://meta.discourse.org/t/change-topic-timestamp-results-in-403-forbidden/52312/6)

```ruby
class ::Guardian
    module CanSeeTopic
      def can_see_topic?(topic, hide_deleted=true)
        super || topic.archetype == Archetype.chat && (can_see?(topic.category) || topic.allowed_group_users.include?(user))
      end
    end
    prepend CanSeeTopic
  end
```

**Comment by kgish** [comment]
See the following pull request [#4538](https://github.com/discourse/discourse/pull/4538)

Once this has been (hopefully) accepted and updated in a later release, I can replace the following work-around guardian with the one below.

**Comment by Socioneers** [comment]
Looks to work on test

**Comment by kgish** [comment]
Cool, move to completed.

**Comment by kgish** [comment]
Waiting for pull request to be integrated into discourse on next release.
