### ISSUE TITLE
Annotation sometimes not appearing and/ or saving

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#91]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type

> i.getLastTextNodeUpTo()
> application-fe7e5b51c5632cef81e17ac48af641117f7ac581b1108fad3c85d17dded76a61.js:64
> n.BrowserRange</e.prototype.normalize()
> application-fe7e5b51c5632cef81e17ac48af641117f7ac581b1108fad3c85d17dded76a61.js:65
> t</r.prototype.getSelectedRanges/s<()
> application-fe7e5b51c5632cef81e17ac48af641117f7ac581b1108fad3c85d17dded76a61.js:65
> t</r.prototype.getSelectedRanges()
> application-fe7e5b51c5632cef81e17ac48af641117f7ac581b1108fad3c85d17dded76a61.js:65
> t</r.prototype.checkForEndSelection()
> application-fe7e5b51c5632cef81e17ac48af641117f7ac581b1108fad3c85d17dded76a61.js:65
> L/<()
> application-fe7e5b51c5632cef81e17ac48af641117f7ac581b1108fad3c85d17dded76a61.js:64
> oe.event.dispatch()
> ember_jquery-5bc98ec46a799a78ead48d23df534d67c737906cdc100d826b0a001a8a1c1b8b.js:2
> oe.event.add/v.handle()

 
![image004](https://cloud.githubusercontent.com/assets/11832800/19857914/c3057786-9f7f-11e6-8ec1-474fcf3b7d4a.png)
![image003](https://cloud.githubusercontent.com/assets/11832800/19857915/c309999c-9f7f-11e6-946a-c963b3e0ab3a.png)
![image002](https://cloud.githubusercontent.com/assets/11832800/19857916/c30c22b6-9f7f-11e6-8b54-525a706c5c49.png)
![image001](https://cloud.githubusercontent.com/assets/11832800/19857917/c30f3ffa-9f7f-11e6-9a65-c32e4fb4c645.png)

**Comment by kgish** [comment]
Do not see any relationship with the title of this issue and the screenshots, each of which has to do with something else.

**Comment by Socioneers** [comment]
It seems that you made this issue, so you know best.

But this was also in the error message-mail I send:

‘mozHidden’ en ‘mozVisibilityState’ worden niet meer ondersteund. Gebruik in plaats daarvan ‘hidden’ en ‘visibilityState’.
 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type>

**Comment by kgish** [comment]
Yes it was indeed a late night copy/paste episode. Just trying to help move things along as we should avoid putting these in emails and create issues instead.

Just took the error message in the email and added the screenshots that went with along with it.

However, I was confused because I do not see any evidence of this error in any of the screenshots, and cannot conclude where and how this error message is produced.

**Comment by Socioneers** [comment]
Problems:
1) amendements not showing on page, after several times of refreshing they do
2) user gets white sidebar, sometimes takes 10 minutes before its gone
3) user makes annotation but opslaan (saving) does not happen and work
<img width="689" alt="screen shot 2016-11-02 at 20 45 54" src="https://cloud.githubusercontent.com/assets/11832800/19944766/6c871440-a13d-11e6-8fee-18e883683699.png">

**Comment by kgish** [comment]
Weird, this doesn't happen with me, perhaps I need to login as another person...

Is this a normal user? Which user? Any errors in the console? If so please send me screenshot included line numbers (far right).

**Comment by Socioneers** [comment]
The previous one was from a pvda user, all the previous screen shots and code are related to this problem.

Next screenshots are from me, I just reproduced, when annotations are not saving and popup is not displaying as supposed to be.

<img width="1280" alt="screen shot 2016-11-02 at 20 50 00" src="https://cloud.githubusercontent.com/assets/11832800/19945143/20089880-a13f-11e6-9a9e-3328a6422b8f.png">
<img width="1920" alt="screen shot 2016-11-02 at 20 51 01 2" src="https://cloud.githubusercontent.com/assets/11832800/19945166/33d9a552-a13f-11e6-84b6-400564905c18.png">
<img width="1920" alt="screen shot 2016-11-02 at 20 51 19 2" src="https://cloud.githubusercontent.com/assets/11832800/19945181/4774b282-a13f-11e6-8430-d73c03cf5fad.png">
<img width="1920" alt="screen shot 2016-11-02 at 20 51 30 2" src="https://cloud.githubusercontent.com/assets/11832800/19945198/5c7548b8-a13f-11e6-8338-d8490ccfde0a.png">
<img width="1920" alt="screen shot 2016-11-02 at 20 51 42 2" src="https://cloud.githubusercontent.com/assets/11832800/19945208/64649812-a13f-11e6-9cf9-05a57997ec60.png">
<img width="1280" alt="screen shot 2016-11-02 at 20 51 42" src="https://cloud.githubusercontent.com/assets/11832800/19945215/6cdaf216-a13f-11e6-87ab-663bfdc9773a.png">
<img width="1920" alt="screen shot 2016-11-02 at 20 52 23 2" src="https://cloud.githubusercontent.com/assets/11832800/19945223/74d957b4-a13f-11e6-90c5-1fd0d2f19fe7.png">
<img width="1920" alt="screen shot 2016-11-02 at 20 52 32 2" src="https://cloud.githubusercontent.com/assets/11832800/19945231/81d873c8-a13f-11e6-8ef1-f6c5373c7906.png">
<img width="1920" alt="screen shot 2016-11-02 at 20 52 37 2" src="https://cloud.githubusercontent.com/assets/11832800/19945240/8a57e2e0-a13f-11e6-807a-ebccb037ce52.png">
<img width="1920" alt="screen shot 2016-11-02 at 20 53 11 2" src="https://cloud.githubusercontent.com/assets/11832800/19945248/95dbe080-a13f-11e6-915c-b0f185aab6f0.png">
<img width="1280" alt="screen shot 2016-11-02 at 20 53 11" src="https://cloud.githubusercontent.com/assets/11832800/19945251/9c3043fe-a13f-11e6-9097-b6748cecfcf9.png">
<img width="1920" alt="screen shot 2016-11-02 at 20 53 29 2" src="https://cloud.githubusercontent.com/assets/11832800/19945261/a7f1a3f4-a13f-11e6-9e02-069e3192b89a.png">

**Comment by kgish** [comment]
Excellent! Still kinda weird that I cannot reproduce any of this, wonder what I'm doing wrong.

Looks like the annotator is choking sometimes whereby an exception causes all progress to be aborted, this I can fix.

You can ignore the 403 errors which has to do with another issue (which is a security feature) and has to do with only admins allowed to change topic timestamps and awaiting support from forum.

These are merely errors and not exceptions so that the flow is not disrupted and progress allowed to continue.

Let me have a look....

**Comment by Socioneers** [comment]
Amendments are not saving on production. Only error I see is >`Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError`

**Comment by kgish** [comment]
You mean annotations, right?

Cannot reproduce (as kiffin/admin and kiffin1/pvda), please provide me with a user and topic id I can reproduce it on.

**Comment by Socioneers** [comment]
Yes annotations> Looks likea limit on users, it happens with users that used the function a lot.

**Comment by kgish** [comment]
Looks like a Mac thing, see http://stackoverflow.com/questions/31358446/failed-to-clear-temp-storage

**Comment by Socioneers** [comment]
PvdA moderator has the same issue

**Comment by kgish** [comment]
Try instructions I sent in previous comment and see if that helps.
