### ISSUE TITLE
Multiple categories don't work

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#92]
Hi,

I made you test sub-cat's here
https://ledenkamer.pvda.nl/c/Amendeer-verkiezingsprogramma-2017/test-amenderen
https://ledenkamer.pvda.nl/c/Moties-congres-2017/test-motie

I hope this is help full, it is not working to have multiple cat’s for the annotator plugin in production.

Cheers,
Raoul

**Comment by kgish** [comment]
Can you please tell me what doesn't work?

**Comment by kgish** [comment]
@Socioneers : please explain.

**Comment by Socioneers** [comment]
Not important now.
