### ISSUE TITLE
Annotation not appearing sometimes

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#95]
On production the annotations sometimes do not appear, could be something to do with performance and/or loading issues.

Cannot reproduce.

**Comment by kgish** [comment]
@Socioneers : Do you mean the annotations in the text? The sidebar? Something else?

I am unable to reproduce this using the test links you sent me.

Please create an issue with step-by-step instructions.

**Comment by Socioneers** [comment]
related to #91 I will try to add more examples
