### ISSUE TITLE
Meest gesteund in wrong cat

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-annotator-plugin#99]
Meest gesteund should be visible in amendment category.
<img width="1165" alt="screen shot 2016-11-04 at 10 55 37" src="https://cloud.githubusercontent.com/assets/11832800/20001650/82dd78ce-a27d-11e6-8874-c9e36a20cb43.png">
<img width="1158" alt="screen shot 2016-11-04 at 10 55 52" src="https://cloud.githubusercontent.com/assets/11832800/20001649/82dd5a6a-a27d-11e6-8710-3d7c8588a3ac.png">

**Comment by kgish** [comment]
Picked it up.

**Comment by kgish** [comment]
This was already working with the previous bundled fixes, please verify.

**Comment by Socioneers** [comment]
on production button seems to be still in the wrong category

**Comment by kgish** [comment]
Bummer, I'll look into it right away.
